# Generated by Django 3.1 on 2022-04-21 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('E-bike', 'E-bike'), ('Bike', 'Bike'), ('Other', 'Other')], default='Bike', max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('salePrice', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime(2022, 4, 21, 20, 1, 3, 57998))),
                ('location', models.CharField(choices=[('city', 'city centre'), ('MOA', 'AMFI Moa')], default='city', max_length=4)),
                ('status', models.CharField(choices=[('cart', 'still shopping'), ('paid', 'shopping compleated'), ('done', 'order compleated')], default='cart', max_length=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2022, 4, 21, 20, 1, 3, 58999))),
                ('stars', models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Neutral'), ('4', 'Positive'), ('5', 'Excelant')], default='5', max_length=1)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRRR.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRRR.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRRR.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'stars'), name='unique_stars'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'content'), name='unique_review'),
        ),
    ]
