# Generated by Django 3.1 on 2022-04-21 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0002_auto_20220421_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 20, 7, 36, 644054)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 20, 7, 36, 643054)),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
