# Generated by Django 3.1 on 2022-03-25 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0004_alter_comment_comment_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 15, 42, 12, 441400)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 15, 42, 12, 436401)),
        ),
    ]
