# Generated by Django 3.1 on 2022-04-08 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0006_auto_20220408_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 13, 45, 58, 650757)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 13, 45, 58, 649756)),
        ),
    ]
