# Generated by Django 3.1 on 2022-04-14 10:14

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0008_auto_20220414_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 14, 5, 836961)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 14, 5, 835703)),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'stars'), name='unique_stars'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'content'), name='unique_review'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(salePrice__lt=django.db.models.expressions.F('price')), name='discount'),
        ),
    ]
