# Generated by Django 4.0.1 on 2022-04-14 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0008_remove_order_products_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 8, 36, 175750)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 8, 36, 175750)),
        ),
    ]
