# Generated by Django 3.1 on 2022-04-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E-bike', 'E-bike'), ('Bike', 'Bike'), ('Other', 'Other')], default='Bike', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 20, 35, 50, 840708)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 20, 35, 50, 834710)),
        ),
    ]
