# Generated by Django 4.0.1 on 2022-04-21 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('KRRR', '0009_alter_comment_comment_date_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='realized',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'still shopping'), ('paid', 'shopping compleated'), ('done', 'order compleated')], default='cart', max_length=4),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 11, 42, 1, 893280)),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('city', 'city centre'), ('MOA', 'AMFI Moa')], default='city', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 11, 42, 1, 892572)),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'stars'), name='unique_stars'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('customer', 'product', 'content'), name='unique_review'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('salePrice__lt', django.db.models.expressions.F('price'))), name='discount'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRRR.order'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KRRR.product'),
        ),
    ]
